language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aymm/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true aymm/docker-react npm run test