version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "192.168.99.101:3000:3000"
    volumes:
     - /app/node_modules
     - C:/Users/ckckc/udemy/docker-and-kubernetes/frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
     - /app/node_modules
     - C:/Users/ckckc/udemy/docker-and-kubernetes/frontend
    command: ["npm", "run", "test"]